#!/usr/bin/env node
/**
 * Generates public/sw.js with a baked-in cache version (content hash) and
 * the list of files to pre-cache on install. Run from prebuild/predev so
 * the service worker stays in sync with what's actually under public/assets.
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { dirname, join, posix, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const publicDir = join(repoRoot, 'public');
const assetsDir = join(publicDir, 'assets');
const swPath = join(publicDir, 'sw.js');

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (entry.isFile()) {
      files.push(full);
    }
  }
  return files;
}

async function fileHash(path) {
  const buf = await readFile(path);
  return createHash('sha256').update(buf).digest('hex').slice(0, 12);
}

async function collectAssetUrls() {
  let assetFiles = [];
  try {
    assetFiles = await walk(assetsDir);
  } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
  return assetFiles
    .map((p) => '/' + posix.join('assets', relative(assetsDir, p).split(/[\\/]+/).join('/')))
    .sort();
}

async function staticPublicUrls() {
  // Files at the root of /public that the SW should treat as part of the shell.
  const roots = ['manifest.webmanifest', 'icon.svg', 'icon-maskable.svg'];
  const present = [];
  for (const name of roots) {
    try {
      await stat(join(publicDir, name));
      present.push('/' + name);
    } catch {
      /* skip missing optional files */
    }
  }
  return present;
}

async function main() {
  const [assetUrls, staticUrls] = await Promise.all([collectAssetUrls(), staticPublicUrls()]);

  const shellUrls = ['/', '/game', ...staticUrls];
  const precacheUrls = [...new Set([...shellUrls, ...assetUrls])].sort();

  // Hash the precache list so the SW byte-changes whenever inputs change,
  // which is what triggers the browser to install the new worker.
  const versionInput = JSON.stringify(precacheUrls);
  const version = createHash('sha256').update(versionInput).digest('hex').slice(0, 12);

  // Also fold each asset's content hash into the version so an edited asset
  // (same path, new bytes) still bumps the SW.
  const assetHashes = await Promise.all(
    assetUrls.map(async (url) => `${url}@${await fileHash(join(publicDir, url.replace(/^\//, '')))}`)
  );
  const fullVersion = createHash('sha256')
    .update(version + assetHashes.join('|'))
    .digest('hex')
    .slice(0, 12);

  const banner = `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit by hand.\n`;
  const body = SW_TEMPLATE.replace('__CACHE_VERSION__', fullVersion).replace(
    '__PRECACHE_URLS__',
    JSON.stringify(precacheUrls, null, 2)
  );

  await mkdir(publicDir, { recursive: true });
  await writeFile(swPath, banner + body, 'utf8');

  console.log(
    `[generate-sw] wrote ${relative(repoRoot, swPath)} (version ${fullVersion}, ${precacheUrls.length} entries)`
  );
}

const SW_TEMPLATE = `/* eslint-disable */
'use strict';

const CACHE_VERSION = '__CACHE_VERSION__';
const CACHE_NAME = 'reel-precache-' + CACHE_VERSION;
const RUNTIME_CACHE = 'reel-runtime-' + CACHE_VERSION;
const PRECACHE_URLS = __PRECACHE_URLS__;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    // addAll is atomic — if any single request fails the install fails. To keep
    // a flaky CDN from blocking install, fetch each one and skip 4xx/5xx.
    await Promise.all(
      PRECACHE_URLS.map(async (url) => {
        try {
          const req = new Request(url, { cache: 'reload' });
          const res = await fetch(req);
          if (res && (res.ok || res.type === 'opaque')) {
            await cache.put(url, res.clone());
          }
        } catch (_) {
          /* offline at install or asset 404 — non-fatal */
        }
      })
    );
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((key) => key.startsWith('reel-') && key !== CACHE_NAME && key !== RUNTIME_CACHE)
        .map((key) => caches.delete(key))
    );
    await self.clients.claim();
    const clients = await self.clients.matchAll({ includeUncontrolled: true });
    for (const client of clients) {
      client.postMessage({ type: 'reel-pwa:ready', version: CACHE_VERSION });
    }
  })());
});

self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'reel-pwa:skip-waiting') {
    self.skipWaiting();
  } else if (data.type === 'reel-pwa:clear') {
    event.waitUntil((async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key.startsWith('reel-')).map((key) => caches.delete(key)));
      const clients = await self.clients.matchAll({ includeUncontrolled: true });
      for (const client of clients) {
        client.postMessage({ type: 'reel-pwa:cleared' });
      }
    })());
  }
});

function isHtmlRequest(request) {
  if (request.mode === 'navigate') return true;
  const accept = request.headers.get('accept') || '';
  return accept.includes('text/html');
}

function isCacheableAsset(url) {
  if (url.pathname.startsWith('/assets/')) return true;
  if (url.pathname.startsWith('/_next/static/')) return true;
  if (url.pathname === '/manifest.webmanifest') return true;
  if (url.pathname === '/icon.svg' || url.pathname === '/icon-maskable.svg') return true;
  return false;
}

function shouldBypass(url) {
  // Don't try to cache server APIs, dev info, or telemetry endpoints —
  // they should fail fast offline rather than being served stale.
  if (url.pathname.startsWith('/api/')) return true;
  if (url.pathname.startsWith('/_next/data/')) return true;
  return false;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (shouldBypass(url)) return;

  if (isHtmlRequest(request)) {
    event.respondWith(networkFirst(request));
    return;
  }

  if (isCacheableAsset(url)) {
    event.respondWith(cacheFirst(request));
    return;
  }
});

async function networkFirst(request) {
  const cache = await caches.open(RUNTIME_CACHE);
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      cache.put(request, response.clone()).catch(() => {});
    }
    return response;
  } catch (err) {
    const cached = await caches.match(request, { ignoreSearch: true });
    if (cached) return cached;
    // Fall back to the closest shell entry so the app can boot offline even
    // for routes we didn't pre-cache (e.g. /game?seed=abc).
    const shellMatch =
      (await caches.match(new URL(request.url).pathname)) ||
      (await caches.match('/game')) ||
      (await caches.match('/'));
    if (shellMatch) return shellMatch;
    throw err;
  }
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const cache = await caches.open(RUNTIME_CACHE);
  const response = await fetch(request);
  if (response && (response.ok || response.type === 'opaque')) {
    cache.put(request, response.clone()).catch(() => {});
  }
  return response;
}
`;

main().catch((err) => {
  console.error('[generate-sw] failed:', err);
  process.exit(1);
});
